target=text.o
libraries=gl glu

CC=gcc
CFLAGS=-O0 -Wall -pedantic

CFLAGS:=$(shell pkg-config --cflags $(libraries)) $(CFLAGS)
LDLIBS:=$(shell pkg-config --libs $(libraries)) $(LDLIBS)

.PHONY: default clean
default: $(target)
clean::
	-rm $(target)
	-rm text.c

text.c: text.rb
	ruby $< > $@

