target=main.o
ifdef USE_GLEW
libraries=sdl2 glew
else
libraries=sdl2 gl glu
endif

CC=gcc
CFLAGS=-O0 -Wall -pedantic

CFLAGS:=$(shell pkg-config --cflags $(libraries)) $(CFLAGS)
LDLIBS:=$(shell pkg-config --libs $(libraries)) $(LDLIBS)

.PHONY: default clean
default: $(target)
clean::
	-rm $(target)

